spring:
  config:
    activate:
      on-profile: test
management:
  metrics:
    export:
      datadog:
        enabled: false
logging:
  level:
    root: TRACE
    org.springframework: TRACE
    example: TRACE
